from enum import Enum

class TraceEventType(str, Enum):
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    TOOL_CALLED = "TOOL_CALLED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    RETRY_TRIGGERED = "RETRY_TRIGGERED"
    CONTEXT_COMPRESSED = "CONTEXT_COMPRESSED"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    SYNTHESIS_COMPLETED = "SYNTHESIS_COMPLETED"
    ROUTING_DECISION = "ROUTING_DECISION"
